[package]
name = "lending_protocol_usdc"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }